baseURL = ''
languageCode = 'en-us'
title = 'Jidin Dinesh'
paginate = 1000
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = 'assets/favicon.ico'
  description = "Jidin Dinesh's corner of the interweb."
  author = 'jidin'


[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Writing"
    url = "/blog/"
    weight = 1
 # [[menu.main]]
 #   identifier = "books"
 #   name = "Reading"
  #  url = "/books/"
 #   weight = 2
  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
    weight = 3
  [[menu.main]]
    identifier = "quotes"
    name = "Quotes"
    url = "/quotes/"
    weight = 4

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
